package gui_cadastro;

import javax.swing.JOptionPane;

public class JFrameCadDependentes extends javax.swing.JFrame {

    Dependente dep = new Dependente();
    static JFrameCadastro frameCadastro;
    static Socio socio = new Socio();
    static int linha;
    
    
    public JFrameCadDependentes() {
        initComponents();
    }
    
    public JFrameCadDependentes(JFrameCadastro frameCadastro, Socio socio, int linha){
        initComponents();
        this.frameCadastro = frameCadastro;
        this.socio = socio;
        this.linha = linha;
        tfCodigoDependente.setText(String.valueOf(socio.getCodigo()+1) + (linha<9? ".0":".") + String.valueOf(linha + 1));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnCadDep = new javax.swing.JPanel();
        lblCodigoDep = new javax.swing.JLabel();
        lblDataNascDep = new javax.swing.JLabel();
        lblNomeDep = new javax.swing.JLabel();
        btnCadastrarDep = new javax.swing.JButton();
        btnLimparDep = new javax.swing.JButton();
        lblCancelarDep = new javax.swing.JButton();
        tfCodigoDependente = new javax.swing.JTextField();
        tfNomeDependente = new javax.swing.JTextField();
        ftfDataNascDep = new javax.swing.JFormattedTextField();
        cbPcdDependente = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Dependentes");
        setResizable(false);

        pnCadDep.setBackground(new java.awt.Color(45, 45, 45));
        pnCadDep.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dependente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("URW Gothic", 1, 14), java.awt.Color.white)); // NOI18N
        pnCadDep.setForeground(java.awt.Color.white);

        lblCodigoDep.setFont(new java.awt.Font("URW Gothic", 1, 14)); // NOI18N
        lblCodigoDep.setForeground(java.awt.Color.white);
        lblCodigoDep.setText("Código");

        lblDataNascDep.setFont(new java.awt.Font("URW Gothic", 1, 14)); // NOI18N
        lblDataNascDep.setForeground(java.awt.Color.white);
        lblDataNascDep.setText("Data de Nascimento");

        lblNomeDep.setFont(new java.awt.Font("URW Gothic", 1, 14)); // NOI18N
        lblNomeDep.setForeground(java.awt.Color.white);
        lblNomeDep.setText("Nome");

        btnCadastrarDep.setBackground(new java.awt.Color(95, 95, 95));
        btnCadastrarDep.setFont(new java.awt.Font("URW Gothic", 0, 14)); // NOI18N
        btnCadastrarDep.setForeground(java.awt.Color.white);
        btnCadastrarDep.setText("Cadastrar");
        btnCadastrarDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarDepActionPerformed(evt);
            }
        });

        btnLimparDep.setBackground(new java.awt.Color(95, 95, 95));
        btnLimparDep.setFont(new java.awt.Font("URW Gothic", 0, 14)); // NOI18N
        btnLimparDep.setForeground(java.awt.Color.white);
        btnLimparDep.setText("Limpar");
        btnLimparDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparDepActionPerformed(evt);
            }
        });

        lblCancelarDep.setBackground(new java.awt.Color(95, 95, 95));
        lblCancelarDep.setFont(new java.awt.Font("URW Gothic", 0, 14)); // NOI18N
        lblCancelarDep.setForeground(java.awt.Color.white);
        lblCancelarDep.setText("Cancelar");
        lblCancelarDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblCancelarDepActionPerformed(evt);
            }
        });

        tfCodigoDependente.setBackground(new java.awt.Color(81, 81, 81));
        tfCodigoDependente.setFont(new java.awt.Font("URW Gothic", 1, 14)); // NOI18N
        tfCodigoDependente.setForeground(java.awt.Color.white);
        tfCodigoDependente.setEnabled(false);

        tfNomeDependente.setBackground(new java.awt.Color(81, 81, 81));
        tfNomeDependente.setFont(new java.awt.Font("URW Gothic", 1, 14)); // NOI18N
        tfNomeDependente.setForeground(java.awt.Color.white);

        ftfDataNascDep.setBackground(new java.awt.Color(81, 81, 81));
        ftfDataNascDep.setForeground(java.awt.Color.white);
        try {
            ftfDataNascDep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfDataNascDep.setFont(new java.awt.Font("URW Gothic", 1, 14)); // NOI18N

        cbPcdDependente.setBackground(new java.awt.Color(45, 45, 45));
        cbPcdDependente.setFont(new java.awt.Font("URW Gothic", 1, 14)); // NOI18N
        cbPcdDependente.setForeground(java.awt.Color.white);

        jLabel1.setBackground(new java.awt.Color(45, 45, 45));
        jLabel1.setFont(new java.awt.Font("URW Gothic", 1, 14)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("PCD");

        javax.swing.GroupLayout pnCadDepLayout = new javax.swing.GroupLayout(pnCadDep);
        pnCadDep.setLayout(pnCadDepLayout);
        pnCadDepLayout.setHorizontalGroup(
            pnCadDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCadDepLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnCadDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnCadDepLayout.createSequentialGroup()
                        .addComponent(lblCancelarDep)
                        .addGap(59, 59, 59)
                        .addComponent(btnLimparDep)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCadastrarDep))
                    .addGroup(pnCadDepLayout.createSequentialGroup()
                        .addGroup(pnCadDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomeDep)
                            .addComponent(lblCodigoDep)
                            .addComponent(jLabel1))
                        .addGap(20, 20, 20)
                        .addGroup(pnCadDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNomeDependente, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnCadDepLayout.createSequentialGroup()
                                .addComponent(tfCodigoDependente, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(lblDataNascDep)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftfDataNascDep))
                            .addComponent(cbPcdDependente))))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pnCadDepLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCadastrarDep, btnLimparDep, lblCancelarDep});

        pnCadDepLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblCodigoDep, lblNomeDep});

        pnCadDepLayout.setVerticalGroup(
            pnCadDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCadDepLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnCadDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataNascDep)
                    .addComponent(lblCodigoDep)
                    .addComponent(ftfDataNascDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCodigoDependente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnCadDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeDep)
                    .addComponent(tfNomeDependente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(pnCadDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbPcdDependente)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(pnCadDepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarDep)
                    .addComponent(btnLimparDep)
                    .addComponent(lblCancelarDep))
                .addGap(25, 25, 25))
        );

        pnCadDepLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCadastrarDep, btnLimparDep, lblCancelarDep});

        pnCadDepLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblCodigoDep, lblNomeDep});

        pnCadDepLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ftfDataNascDep, tfCodigoDependente});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnCadDep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnCadDep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarDepActionPerformed
        Data data = new Data();
        boolean checagem = false;
        String mensagemErro = "";
        
        if(tfNomeDependente.getText().equals("")){
        checagem = false;
        mensagemErro += "\nObrigatório preencher o Nome";
        }
        if(ftfDataNascDep.getText().charAt(0) == ' '){
            mensagemErro += "Obrigatório preencher a Data de Nascimento\n";
                checagem = false;
        }else{
            data.setDia(Integer.parseInt(ftfDataNascDep.getText().substring(0,2)));
            data.setMes(Integer.parseInt(ftfDataNascDep.getText().substring(3,5)));
            data.setAno(Integer.parseInt(ftfDataNascDep.getText().substring(6,10)));
        }
        if(!checagem){
            JOptionPane.showMessageDialog(null, mensagemErro);
        }else{
            dep.setCod(tfCodigoDependente.getText());
            dep.setNome(tfNomeDependente.getText());
            dep.setDataNasc(data);
            frameCadastro.setState(JFrameCadastro.NORMAL);
            frameCadastro.tDependentesCadastrar(dep, linha);
            dispose();
        }
    }//GEN-LAST:event_btnCadastrarDepActionPerformed

    
    private void btnLimparDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparDepActionPerformed
        ftfDataNascDep.setText(null);
        tfNomeDependente.setText(null);
        tfCodigoDependente.setText(null);
        cbPcdDependente.setSelected(false);
    }//GEN-LAST:event_btnLimparDepActionPerformed

    private void lblCancelarDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblCancelarDepActionPerformed
        dispose();
    }//GEN-LAST:event_lblCancelarDepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCadDependentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCadDependentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCadDependentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCadDependentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCadDependentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarDep;
    private javax.swing.JButton btnLimparDep;
    private javax.swing.JCheckBox cbPcdDependente;
    private javax.swing.JFormattedTextField ftfDataNascDep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton lblCancelarDep;
    private javax.swing.JLabel lblCodigoDep;
    private javax.swing.JLabel lblDataNascDep;
    private javax.swing.JLabel lblNomeDep;
    private javax.swing.JPanel pnCadDep;
    private javax.swing.JTextField tfCodigoDependente;
    private javax.swing.JTextField tfNomeDependente;
    // End of variables declaration//GEN-END:variables
}
