package gui_cadastro;

import java.awt.Color;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;

public class JFrameCadastro extends javax.swing.JFrame {

    static Socio socio = new Socio();
    static int nroDependentesCadastrados = 0;
    ArrayList<Dependente> auxDeps = new ArrayList<Dependente>();
    static int linha = 0;
    JFrameCadDependentes fCadDep;
    
    public JFrameCadastro() {
        initComponents();
    }
    public JFrameCadastro(Socio s, int tipo){
        initComponents();
        socio = s;
        
        if(tipo == 1){ //Cadastro
            tfCodigo.setText(String.valueOf(socio.getCodigo() + 1));
        }else{
            Data dataAuxEditar = new Data();
             String auxAtividades;
             
             tfCodigo.setText(String.valueOf(socio.getCodigo()));
             tfNome.setText(socio.getNome());
             ftfCPF.setText(socio.getCpf());
             tfRG.setText(socio.getRg());
             radioFeminino.setSelected(socio.getGenero() == "Feminino");
             radioMasculino.setSelected(socio.getGenero() == "Masculino");
             ftfDataNasc.setText(String.valueOf(socio.getDataNasc().getDia()) + "/" + String.valueOf(socio.getDataNasc().getMes()) + "/" + String.valueOf(socio.getDataNasc().getAno()));
             cbSocioProprietario.setSelected(socio.isSocioProprietario());
             cbPCD.setSelected(socio.isPcd());
             tfEmail.setText(socio.getEmail());
             tfLogradouro.setText(socio.getEndereco().getLogradouro());
             tfNumero.setText(String.valueOf(socio.getEndereco().getNro()));
             tfCidade.setText(socio.getEndereco().getCidade());
             tfBairro.setText(socio.getEndereco().getBairro());
             cbEstado.setSelectedItem(socio.getEndereco().getEstado());
             ftfCEP.setText(socio.getEndereco().getCep());
             btnCadastrarDependentes.setEnabled(false);
             nroDependentesCadastrados = socio.getNroDependentes();
             
             for(int i=0; i< nroDependentesCadastrados; i++){
                 dataAuxEditar = socio.getDependentes().get(i).getDataNasc();
                 tDeps.setValueAt(socio.getDependentes().get(i).getCod(),i,0);
                 tDeps.setValueAt(socio.getDependentes().get(i).getNome(), i,1);
                 tDeps.setValueAt(dataAuxEditar.getDia() + "/" + dataAuxEditar.getMes() + "/" + dataAuxEditar.getAno(), i,2);
                 tDeps.setValueAt(socio.getDependentes().get(i).isPcd(rootPaneCheckingEnabled), i,3);
             }
            lAtividades.clearSelection();
            auxAtividades = socio.getAtividades();
            
            int indices[] = new int[lAtividades.getModel().getSize()];
            
            int k=0;
            for(int i = 0; i<lAtividades.getModel().getSize(); i++){
                if(auxAtividades.contains(lAtividades.getModel().getElementAt(i))){
                    indices[k] += i;
                    k++;
                }
            }
            lAtividades.setSelectedIndices(indices);
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgGenero = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox<>();
        lblO2 = new javax.swing.JLabel();
        pnDados = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        lblRG = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        lblDataNasc = new javax.swing.JLabel();
        radioMasculino = new javax.swing.JRadioButton();
        radioFeminino = new javax.swing.JRadioButton();
        cbSocioProprietario = new javax.swing.JCheckBox();
        tfCodigo = new javax.swing.JTextField();
        tfNome = new javax.swing.JTextField();
        cbPCD = new javax.swing.JCheckBox();
        ftfCPF = new javax.swing.JFormattedTextField();
        ftfDataNasc = new javax.swing.JFormattedTextField();
        tfRG = new javax.swing.JTextField();
        pnEndereco = new javax.swing.JPanel();
        lblLogradouro = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        ftfCEP = new javax.swing.JFormattedTextField();
        lblCEP = new javax.swing.JLabel();
        tfLogradouro = new javax.swing.JTextField();
        tfNumero = new javax.swing.JTextField();
        tfBairro = new javax.swing.JTextField();
        tfCidade = new javax.swing.JTextField();
        cbEstado = new javax.swing.JComboBox<>();
        lblEmail = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        btnSairCadastrar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        lblQtdeDependentes = new javax.swing.JLabel();
        lblAtividades = new javax.swing.JLabel();
        cbQtdeDependentes = new javax.swing.JComboBox<>();
        btnCadastrarDependentes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tDeps = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        lAtividades = new javax.swing.JList<>();
        lblO = new javax.swing.JLabel();
        lblO1 = new javax.swing.JLabel();
        lblO3 = new javax.swing.JLabel();
        lblO4 = new javax.swing.JLabel();
        lblO7 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblO2.setFont(new java.awt.Font("URW Gothic", 1, 18)); // NOI18N
        lblO2.setForeground(new java.awt.Color(255, 51, 255));
        lblO2.setText("*");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro");
        setResizable(false);

        pnDados.setBackground(new java.awt.Color(45, 45, 45));
        pnDados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("URW Gothic", 0, 18), java.awt.Color.white)); // NOI18N
        pnDados.setForeground(java.awt.Color.white);
        pnDados.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        lblCodigo.setFont(new java.awt.Font("URW Gothic", 1, 14)); // NOI18N
        lblCodigo.setForeground(java.awt.Color.white);
        lblCodigo.setText("Código");

        lblNome.setFont(new java.awt.Font("URW Gothic", 1, 14)); // NOI18N
        lblNome.setForeground(java.awt.Color.white);
        lblNome.setText("Nome");

        lblCPF.setFont(new java.awt.Font("URW Gothic", 1, 14)); // NOI18N
        lblCPF.setForeground(java.awt.Color.white);
        lblCPF.setText("CPF");

        lblRG.setFont(new java.awt.Font("URW Gothic", 1, 14)); // NOI18N
        lblRG.setForeground(java.awt.Color.white);
        lblRG.setText("RG");

        lblGenero.setFont(new java.awt.Font("URW Gothic", 1, 14)); // NOI18N
        lblGenero.setForeground(java.awt.Color.white);
        lblGenero.setText("Gênero");

        lblDataNasc.setFont(new java.awt.Font("URW Gothic", 1, 14)); // NOI18N
        lblDataNasc.setForeground(java.awt.Color.white);
        lblDataNasc.setText("Data de Nascimento");

        radioMasculino.setBackground(new java.awt.Color(45, 45, 45));
        bgGenero.add(radioMasculino);
        radioMasculino.setFont(new java.awt.Font("URW Gothic", 1, 12)); // NOI18N
        radioMasculino.setForeground(java.awt.Color.white);
        radioMasculino.setText("Masculino");
        radioMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioMasculinoActionPerformed(evt);
            }
        });

        radioFeminino.setBackground(new java.awt.Color(45, 45, 45));
        bgGenero.add(radioFeminino);
        radioFeminino.setFont(new java.awt.Font("URW Gothic", 1, 12)); // NOI18N
        radioFeminino.setForeground(java.awt.Color.white);
        radioFeminino.setText("Feminino");
        radioFeminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioFemininoActionPerformed(evt);
            }
        });

        cbSocioProprietario.setBackground(new java.awt.Color(45, 45, 45));
        cbSocioProprietario.setFont(new java.awt.Font("URW Gothic", 1, 14)); // NOI18N
        cbSocioProprietario.setForeground(java.awt.Color.white);
        cbSocioProprietario.setText("Sócio Proprietário");
        cbSocioProprietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSocioProprietarioActionPerformed(evt);
            }
        });

        tfCodigo.setEditable(false);
        tfCodigo.setBackground(new java.awt.Color(81, 81, 81));
        tfCodigo.setFont(new java.awt.Font("URW Gothic", 1, 14)); // NOI18N
        tfCodigo.setForeground(java.awt.Color.white);
        tfCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCodigoActionPerformed(evt);
            }
        });

        tfNome.setBackground(new java.awt.Color(81, 81, 81));
        tfNome.setFont(new java.awt.Font("URW Gothic", 1, 14)); // NOI18N
        tfNome.setForeground(java.awt.Color.white);
        tfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeActionPerformed(evt);
            }
        });

        cbPCD.setBackground(new java.awt.Color(45, 45, 45));
        cbPCD.setFont(new java.awt.Font("URW Gothic", 1, 14)); // NOI18N
        cbPCD.setForeground(java.awt.Color.white);
        cbPCD.setText("PCD");
        cbPCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPCDActionPerformed(evt);
            }
        });

        ftfCPF.setBackground(new java.awt.Color(81, 81, 81));
        ftfCPF.setForeground(java.awt.Color.white);
        try {
            ftfCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfCPF.setFont(new java.awt.Font("URW Gothic", 1, 14)); // NOI18N
        ftfCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfCPFActionPerformed(evt);
            }
        });

        ftfDataNasc.setBackground(new java.awt.Color(81, 81, 81));
        ftfDataNasc.setForeground(java.awt.Color.white);
        try {
            ftfDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfDataNasc.setFont(new java.awt.Font("URW Gothic", 1, 14)); // NOI18N
        ftfDataNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfDataNascActionPerformed(evt);
            }
        });

        tfRG.setBackground(new java.awt.Color(81, 81, 81));
        tfRG.setFont(new java.awt.Font("URW Gothic", 1, 14)); // NOI18N
        tfRG.setForeground(java.awt.Color.white);
        tfRG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRGActionPerformed(evt);
            }
        });

        pnEndereco.setBackground(new java.awt.Color(45, 45, 45));
        pnEndereco.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereço", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("URW Gothic", 0, 14), java.awt.Color.white)); // NOI18N
        pnEndereco.setForeground(java.awt.Color.white);

        lblLogradouro.setFont(new java.awt.Font("URW Gothic", 1, 14)); // NOI18N
        lblLogradouro.setForeground(java.awt.Color.white);
        lblLogradouro.setText("Logradouro");

        lblNumero.setFont(new java.awt.Font("URW Gothic", 1, 14)); // NOI18N
        lblNumero.setForeground(java.awt.Color.white);
        lblNumero.setText("Nº");

        lblEstado.setFont(new java.awt.Font("URW Gothic", 1, 14)); // NOI18N
        lblEstado.setForeground(java.awt.Color.white);
        lblEstado.setText("Estado");

        lblCidade.setFont(new java.awt.Font("URW Gothic", 1, 14)); // NOI18N
        lblCidade.setForeground(java.awt.Color.white);
        lblCidade.setText("Cidade");

        lblBairro.setFont(new java.awt.Font("URW Gothic", 1, 14)); // NOI18N
        lblBairro.setForeground(java.awt.Color.white);
        lblBairro.setText("Bairro");

        ftfCEP.setBackground(new java.awt.Color(81, 81, 81));
        ftfCEP.setForeground(java.awt.Color.white);
        try {
            ftfCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfCEP.setFont(new java.awt.Font("URW Gothic", 1, 14)); // NOI18N
        ftfCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftfCEPActionPerformed(evt);
            }
        });

        lblCEP.setFont(new java.awt.Font("URW Gothic", 1, 14)); // NOI18N
        lblCEP.setForeground(java.awt.Color.white);
        lblCEP.setText("CEP");

        tfLogradouro.setBackground(new java.awt.Color(81, 81, 81));
        tfLogradouro.setFont(new java.awt.Font("URW Gothic", 1, 14)); // NOI18N
        tfLogradouro.setForeground(java.awt.Color.white);
        tfLogradouro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLogradouroActionPerformed(evt);
            }
        });

        tfNumero.setBackground(new java.awt.Color(81, 81, 81));
        tfNumero.setFont(new java.awt.Font("URW Gothic", 1, 14)); // NOI18N
        tfNumero.setForeground(java.awt.Color.white);
        tfNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNumeroActionPerformed(evt);
            }
        });

        tfBairro.setBackground(new java.awt.Color(81, 81, 81));
        tfBairro.setFont(new java.awt.Font("URW Gothic", 1, 14)); // NOI18N
        tfBairro.setForeground(java.awt.Color.white);
        tfBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBairroActionPerformed(evt);
            }
        });

        tfCidade.setBackground(new java.awt.Color(81, 81, 81));
        tfCidade.setFont(new java.awt.Font("URW Gothic", 1, 14)); // NOI18N
        tfCidade.setForeground(java.awt.Color.white);
        tfCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCidadeActionPerformed(evt);
            }
        });

        cbEstado.setBackground(new java.awt.Color(81, 81, 81));
        cbEstado.setFont(new java.awt.Font("URW Gothic", 1, 14)); // NOI18N
        cbEstado.setForeground(java.awt.Color.white);
        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PR", "PB", "PA", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SE", "SP", "TO" }));
        cbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnEnderecoLayout = new javax.swing.GroupLayout(pnEndereco);
        pnEndereco.setLayout(pnEnderecoLayout);
        pnEnderecoLayout.setHorizontalGroup(
            pnEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEnderecoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblLogradouro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblBairro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnEnderecoLayout.createSequentialGroup()
                        .addComponent(tfLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblNumero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnEnderecoLayout.createSequentialGroup()
                        .addGroup(pnEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfBairro)
                            .addComponent(cbEstado, 0, 132, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pnEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCidade)
                            .addComponent(lblCEP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCidade)
                            .addComponent(ftfCEP))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        pnEnderecoLayout.setVerticalGroup(
            pnEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEnderecoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogradouro)
                    .addComponent(lblNumero)
                    .addComponent(tfLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado)
                    .addComponent(lblCidade)
                    .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCEP)
                        .addComponent(ftfCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBairro)
                        .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pnEnderecoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfBairro, tfLogradouro});

        lblEmail.setFont(new java.awt.Font("URW Gothic", 1, 14)); // NOI18N
        lblEmail.setForeground(java.awt.Color.white);
        lblEmail.setText("Email");

        tfEmail.setBackground(new java.awt.Color(81, 81, 81));
        tfEmail.setFont(new java.awt.Font("URW Gothic", 1, 14)); // NOI18N
        tfEmail.setForeground(java.awt.Color.white);
        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });

        btnSairCadastrar.setBackground(new java.awt.Color(95, 95, 95));
        btnSairCadastrar.setFont(new java.awt.Font("URW Gothic", 0, 16)); // NOI18N
        btnSairCadastrar.setForeground(java.awt.Color.white);
        btnSairCadastrar.setText("Sair");
        btnSairCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairCadastrarActionPerformed(evt);
            }
        });

        btnCadastrar.setBackground(new java.awt.Color(95, 95, 95));
        btnCadastrar.setFont(new java.awt.Font("URW Gothic", 0, 14)); // NOI18N
        btnCadastrar.setForeground(java.awt.Color.white);
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        lblQtdeDependentes.setFont(new java.awt.Font("URW Gothic", 1, 14)); // NOI18N
        lblQtdeDependentes.setForeground(java.awt.Color.white);
        lblQtdeDependentes.setText("Qtde. Dependentes");

        lblAtividades.setFont(new java.awt.Font("URW Gothic", 1, 14)); // NOI18N
        lblAtividades.setForeground(java.awt.Color.white);
        lblAtividades.setText("Atividades");

        cbQtdeDependentes.setBackground(new java.awt.Color(81, 81, 81));
        cbQtdeDependentes.setForeground(java.awt.Color.white);
        cbQtdeDependentes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5" }));
        cbQtdeDependentes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbQtdeDependentesItemStateChanged(evt);
            }
        });
        cbQtdeDependentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbQtdeDependentesActionPerformed(evt);
            }
        });

        btnCadastrarDependentes.setBackground(new java.awt.Color(95, 95, 95));
        btnCadastrarDependentes.setFont(new java.awt.Font("URW Gothic", 0, 14)); // NOI18N
        btnCadastrarDependentes.setForeground(java.awt.Color.white);
        btnCadastrarDependentes.setText("Cadastrar Dependentes");
        btnCadastrarDependentes.setEnabled(false);
        btnCadastrarDependentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarDependentesActionPerformed(evt);
            }
        });

        tDeps.setAutoCreateRowSorter(true);
        tDeps.setBackground(new java.awt.Color(81, 81, 81));
        tDeps.setFont(new java.awt.Font("URW Gothic", 0, 14)); // NOI18N
        tDeps.setForeground(java.awt.Color.white);
        tDeps.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Data Nascimento", "PCD"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tDeps);

        lAtividades.setBackground(new java.awt.Color(81, 81, 81));
        lAtividades.setFont(new java.awt.Font("URW Gothic", 0, 14)); // NOI18N
        lAtividades.setForeground(java.awt.Color.white);
        lAtividades.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Academia", "Basquete", "Bibliotéca", "Futebol", "Games", "Jiu-Jitsu", "Karatê", "Muai-Thay", "Natação", "Parque", "Recreação" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lAtividades);

        lblO.setFont(new java.awt.Font("URW Gothic", 1, 18)); // NOI18N
        lblO.setForeground(new java.awt.Color(255, 51, 255));
        lblO.setText("*");

        lblO1.setFont(new java.awt.Font("URW Gothic", 1, 18)); // NOI18N
        lblO1.setForeground(new java.awt.Color(255, 51, 255));
        lblO1.setText("*");

        lblO3.setFont(new java.awt.Font("URW Gothic", 1, 18)); // NOI18N
        lblO3.setForeground(new java.awt.Color(255, 51, 255));
        lblO3.setText("*");

        lblO4.setFont(new java.awt.Font("URW Gothic", 1, 18)); // NOI18N
        lblO4.setForeground(new java.awt.Color(255, 51, 255));
        lblO4.setText("*");

        lblO7.setFont(new java.awt.Font("URW Gothic", 1, 18)); // NOI18N
        lblO7.setForeground(new java.awt.Color(255, 51, 255));
        lblO7.setText("*");

        javax.swing.GroupLayout pnDadosLayout = new javax.swing.GroupLayout(pnDados);
        pnDados.setLayout(pnDadosLayout);
        pnDadosLayout.setHorizontalGroup(
            pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDadosLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblO)
                    .addComponent(lblO1)
                    .addComponent(lblO3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnDadosLayout.createSequentialGroup()
                            .addComponent(lblQtdeDependentes)
                            .addGap(18, 18, 18)
                            .addComponent(cbQtdeDependentes, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(74, 74, 74)
                            .addComponent(btnCadastrarDependentes))
                        .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnDadosLayout.createSequentialGroup()
                                .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDadosLayout.createSequentialGroup()
                                        .addComponent(lblEmail)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnDadosLayout.createSequentialGroup()
                                        .addComponent(lblDataNasc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ftfDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblCPF))
                                .addGap(39, 39, 39)
                                .addComponent(lblRG)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfRG))
                            .addGroup(pnDadosLayout.createSequentialGroup()
                                .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnDadosLayout.createSequentialGroup()
                                        .addComponent(lblCodigo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfCodigo))
                                    .addGroup(pnDadosLayout.createSequentialGroup()
                                        .addComponent(lblNome)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(pnDadosLayout.createSequentialGroup()
                                                .addComponent(ftfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblO4)
                                                .addGap(26, 26, 26))
                                            .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(26, 26, 26)
                                .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbPCD)
                                    .addComponent(cbSocioProprietario)))
                            .addComponent(pnEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnDadosLayout.createSequentialGroup()
                                .addGap(266, 266, 266)
                                .addComponent(lblO7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblGenero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioMasculino)
                                    .addComponent(radioFeminino))
                                .addGap(46, 46, 46))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnDadosLayout.createSequentialGroup()
                        .addComponent(lblAtividades)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSairCadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCadastrar)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pnDadosLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblCodigo, lblNome});

        pnDadosLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCadastrar, btnSairCadastrar});

        pnDadosLayout.setVerticalGroup(
            pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSocioProprietario)
                    .addComponent(lblO))
                .addGap(18, 18, 18)
                .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPCD)
                    .addComponent(lblO1))
                .addGap(18, 18, 18)
                .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPF)
                    .addComponent(lblRG)
                    .addComponent(ftfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblO3)
                    .addComponent(lblO4))
                .addGap(18, 18, 18)
                .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDadosLayout.createSequentialGroup()
                        .addComponent(radioFeminino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioMasculino))
                    .addGroup(pnDadosLayout.createSequentialGroup()
                        .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDataNasc)
                            .addComponent(lblGenero)
                            .addComponent(ftfDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblO7))
                        .addGap(18, 18, 18)
                        .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail)
                            .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34)
                .addComponent(pnEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQtdeDependentes)
                    .addComponent(cbQtdeDependentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrarDependentes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnDadosLayout.createSequentialGroup()
                        .addComponent(lblAtividades)
                        .addGap(12, 12, 12)
                        .addGroup(pnDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSairCadastrar)
                            .addComponent(btnCadastrar)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pnDadosLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblCodigo, lblNome});

        pnDadosLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblCPF, lblGenero, lblRG});

        pnDadosLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ftfCPF, tfRG});

        pnDadosLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCadastrar, btnSairCadastrar});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ftfDataNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfDataNascActionPerformed
        ftfDataNasc.setForeground(Color.WHITE);
    }//GEN-LAST:event_ftfDataNascActionPerformed

    private void ftfCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfCPFActionPerformed
        ftfCPF.setForeground(Color.WHITE);
    }//GEN-LAST:event_ftfCPFActionPerformed

    private void cbSocioProprietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSocioProprietarioActionPerformed
        cbSocioProprietario.setForeground(Color.WHITE);
    }//GEN-LAST:event_cbSocioProprietarioActionPerformed

    private void tfCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCodigoActionPerformed
        tfCodigo.setForeground(Color.WHITE);
    }//GEN-LAST:event_tfCodigoActionPerformed

    private void tfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeActionPerformed
        tfNome.setForeground(Color.WHITE);
    }//GEN-LAST:event_tfNomeActionPerformed

    private void tfRGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRGActionPerformed
        tfRG.setForeground(Color.WHITE);
    }//GEN-LAST:event_tfRGActionPerformed

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        tfEmail.setForeground(Color.WHITE);
    }//GEN-LAST:event_tfEmailActionPerformed

    private void radioFemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioFemininoActionPerformed
        radioFeminino.setForeground(Color.WHITE);
    }//GEN-LAST:event_radioFemininoActionPerformed

    private void cbPCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPCDActionPerformed
        cbPCD.setForeground(Color.WHITE);
    }//GEN-LAST:event_cbPCDActionPerformed

    private void radioMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioMasculinoActionPerformed
        radioMasculino.setForeground(Color.WHITE);
    }//GEN-LAST:event_radioMasculinoActionPerformed

    private void tfLogradouroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLogradouroActionPerformed
        tfLogradouro.setForeground(Color.WHITE);
    }//GEN-LAST:event_tfLogradouroActionPerformed

    private void tfBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBairroActionPerformed
        tfBairro.setForeground(Color.WHITE);
    }//GEN-LAST:event_tfBairroActionPerformed

    private void tfCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCidadeActionPerformed
        tfCidade.setForeground(Color.WHITE);
    }//GEN-LAST:event_tfCidadeActionPerformed

    private void tfNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNumeroActionPerformed
        tfNumero.setForeground(Color.WHITE);
    }//GEN-LAST:event_tfNumeroActionPerformed

    private void ftfCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftfCEPActionPerformed
        ftfCEP.setForeground(Color.WHITE);
    }//GEN-LAST:event_ftfCEPActionPerformed

    private void btnSairCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairCadastrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairCadastrarActionPerformed

    private void cbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEstadoActionPerformed
        cbEstado.setForeground(Color.WHITE);
    }//GEN-LAST:event_cbEstadoActionPerformed

    private void cbQtdeDependentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbQtdeDependentesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbQtdeDependentesActionPerformed

    private void btnCadastrarDependentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarDependentesActionPerformed
        JFrameCadDependentes jfcadDependente = new JFrameCadDependentes(this, socio, linha);
        jfcadDependente.setVisible(true);
        jfcadDependente.setLocationRelativeTo(null);
        jfcadDependente.getContentPane().setBackground(Color.darkGray);
    }//GEN-LAST:event_btnCadastrarDependentesActionPerformed

    private void cbQtdeDependentesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbQtdeDependentesItemStateChanged
        if(nroDependentesCadastrados < cbQtdeDependentes.getSelectedIndex()){
            btnCadastrarDependentes.setEnabled(true);
        }else{
            btnCadastrarDependentes.setEnabled(false);
        }
    }//GEN-LAST:event_cbQtdeDependentesItemStateChanged

    public void tDependentesCadastrar(Dependente dep, int linha){
        Data data = dep.getDataNasc();
        String auxData;
        auxData = data.getDia() + "/" + data.getMes() + "/" + data.getAno();
        tDeps.setValueAt(dep.getCod(), linha,0);
        tDeps.setValueAt(dep.getNome(), linha, 1);
        tDeps.setValueAt(auxData, linha, 2);
        tDeps.setValueAt(dep.isPcd(rootPaneCheckingEnabled), linha, 3);
        this.linha++;
        nroDependentesCadastrados++;
        if(nroDependentesCadastrados == cbQtdeDependentes.getSelectedIndex()){
            btnCadastrarDependentes.setEnabled(false);
        }
    }
    
    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        Data data = new Data();
        Endereco endereco = new Endereco();
        boolean checagem = true;
        String mensagemErro = "";
        String auxAtividades = null, auxData;
        boolean checkPCD = false;
        
        if(tfNome.getText().equals("")){
            mensagemErro += "Obrigatório preencher o Nome\n";
                checagem = false;
        }
        if(ftfCPF.getText().charAt(0) == ' '){
            mensagemErro += "Obrigatório preencher o CPF\n";
                checagem = false;
        }
        if(tfRG.getText().equals(" ")){
            mensagemErro += "Obrigatório preencher o RG\n";
                checagem = false;
        }
        if(!radioFeminino.isSelected() && !radioMasculino.isSelected()){
            mensagemErro += "Obrigatório Selecionar o Gênero\n";
                checagem = false;
        }
        if(ftfDataNasc.getText().charAt(0) == ' '){
            mensagemErro += "Obrigatório preencher a Data de Nascimento\n";
                checagem = false;
        }else{
            data.setDia(Integer.parseInt(ftfDataNasc.getText().substring(0,2)));
            data.setMes(Integer.parseInt(ftfDataNasc.getText().substring(3,5)));
            data.setAno(Integer.parseInt(ftfDataNasc.getText().substring(6,10)));
        }
        //-----------------------------^--OBRIGATÒRIOS--^--------------------------------------// finalizado
        
        if(!tfLogradouro.getText().equals("")){
            endereco.setLogradouro(tfLogradouro.getText());
            
                if(!tfNumero.getText().equals("")){
                    endereco.setNro(Integer.parseInt(tfNumero.getText()));
                }
                if(!tfBairro.getText().equals("")){
                    endereco.setBairro(tfBairro.getText());
                }
                if(!tfCidade.getText().equals("")){
                    endereco.setCidade(tfCidade.getText());
                }
                
                //Espaço para corrigir o ESTADO
                if(cbEstado.getSelectedIndex() != ' '){
                    endereco.setEstado((String)cbEstado.getSelectedItem()); 
                }
                
                if(ftfCEP.getText().charAt(0) != ' '){
                    endereco.setCep(ftfCEP.getText());
                }                
        }//Fim ENDERECO()
        
        if(cbQtdeDependentes.getSelectedIndex() != 0){
            
            if(nroDependentesCadastrados != cbQtdeDependentes.getSelectedIndex()){
                checagem = false; 
                checkPCD = false;
                
                    mensagemErro += cbQtdeDependentes.getSelectedIndex() + " dependente(s) declarado(s), mais " + nroDependentesCadastrados + "dependente(s) cadastrado(s)\n";
            }else{
                for(int i=0; i<nroDependentesCadastrados; i++){
                    Dependente dep = new Dependente();
                    Data dataDep = new Data();
                    
                    dep.setCod(String.valueOf(tDeps.getValueAt(i, 0)));
                    dep.setNome(String.valueOf(tDeps.getValueAt(i, 1)));
                    auxData = String.valueOf(tDeps.getValueAt(i, 2));
                    dataDep.setDia(Integer.parseInt(auxData.substring(0,2)));
                    dataDep.setMes(Integer.parseInt(auxData.substring(3,5)));
                    dataDep.setAno(Integer.parseInt(auxData.substring(6,10)));
                    dep.setDataNasc(dataDep);
                    
                    //Teste PCD
                    dep.setPcd(Boolean.getBoolean((String) tDeps.getValueAt(i, 3)));
                    
                    //Adicionando dependente à tabela
                    auxDeps.add(dep);
                }
            }
        } //Fim Cad.deps
        
        for(int i=0; i<lAtividades.getModel().getSize(); i++){
            if(lAtividades.isSelectedIndex(i)){
                auxAtividades += lAtividades.getModel().getElementAt(i) + ", ";
            }
        }//Fim Cad Atividades
        
        if(!checagem){
            JOptionPane.showMessageDialog(null, mensagemErro);
        }else{
            linha = 0;
            socio.setCodigo(Integer.parseInt(tfCodigo.getText()));  
            socio.setNome(tfNome.getText());
            socio.setCpf(ftfCPF.getText());
            socio.setRg(tfRG.getText());
            socio.setEmail(tfEmail.getText());
            
            //Teste Genero
            socio.setGenero(radioFeminino.isSelected()? "Feminino":"Masculino");
            //Teste Genero
            
            socio.setSocioProprietario(cbSocioProprietario.isSelected());
            socio.setPcd(cbPCD.isSelected());
            socio.setDataNasc(data);
            socio.setEndereco(endereco);
            socio.setNroDependentes(nroDependentesCadastrados);
            socio.setDependentes(auxDeps);
            socio.setAtividades(auxAtividades);
            //Fim das relações
            dispose();
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgGenero;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCadastrarDependentes;
    private javax.swing.JButton btnSairCadastrar;
    private javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JCheckBox cbPCD;
    private javax.swing.JComboBox<String> cbQtdeDependentes;
    private javax.swing.JCheckBox cbSocioProprietario;
    private javax.swing.JFormattedTextField ftfCEP;
    private javax.swing.JFormattedTextField ftfCPF;
    private javax.swing.JFormattedTextField ftfDataNasc;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lAtividades;
    private javax.swing.JLabel lblAtividades;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCEP;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDataNasc;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblLogradouro;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblO;
    private javax.swing.JLabel lblO1;
    private javax.swing.JLabel lblO2;
    private javax.swing.JLabel lblO3;
    private javax.swing.JLabel lblO4;
    private javax.swing.JLabel lblO7;
    private javax.swing.JLabel lblQtdeDependentes;
    private javax.swing.JLabel lblRG;
    private javax.swing.JPanel pnDados;
    private javax.swing.JPanel pnEndereco;
    private javax.swing.JRadioButton radioFeminino;
    private javax.swing.JRadioButton radioMasculino;
    private javax.swing.JTable tDeps;
    private javax.swing.JTextField tfBairro;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfLogradouro;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfNumero;
    private javax.swing.JTextField tfRG;
    // End of variables declaration//GEN-END:variables
}
